# Verifying the HZH = X Quantum Gate Identity

---

## Introduction

### 1. Problem Statement
Construct a single-qubit quantum circuit containing the sequence $H \to Z \to H$ and compare its resulting statevector with a circuit containing a single Pauli-X gate ($X$). Then, verify the fundamental quantum gate identity $HZH = X$ algebraically using their corresponding matrix representations.

---

## Quantum Gate Identity

### Single-Qubit Gate Definitions
- **Hadamard Gate ($H$)**: Creates an equal superposition between the computational basis states $|0\rangle$ and $|1\rangle$, mapping the $Z$-basis into the $X$-basis and vice versa.
- **Pauli-Z Gate ($Z$)**: Performs a phase-flip operation, leaving $|0\rangle$ unchanged and flipping the phase of $|1\rangle$ ($Z|0\rangle = |0\rangle, Z|1\rangle = -|1\rangle$).
- **Pauli-X Gate ($X$)**: Performs a bit-flip operation, interchanging $|0\rangle$ and $|1\rangle$ ($X|0\rangle = |1\rangle, X|1\rangle = |0\rangle$).

### The Identity: $HZH = X$
In quantum computing, the Hadamard transformation acts as a basis-change operator that conjugates the Pauli-Z operator into the Pauli-X operator:
$$HZH = X$$
Because the Hadamard gate is self-inverse ($H = H^\dagger = H^{-1}$), this identity equivalently demonstrates that $X$ and $Z$ are unitarily similar under Hadamard conjugation: $HXH = Z$ and $HZH = X$.

### Dual Verification Strategy
The identity is verified across two complementary levels:
1. **Circuit-Level Statevector Verification**: Tests whether applying the sequence $H \to Z \to H$ to the initial ground state $|0\rangle$ produces the identical output statevector as applying the single gate $X$ to $|0\rangle$:
   $$HZH|0\rangle = X|0\rangle = |1\rangle$$
2. **Matrix-Level Operator Verification**: Demonstrates operator equality across the entire 2-dimensional Hilbert space by verifying that the matrix product $H @ Z @ H$ equals the matrix $X$ element-by-element for any arbitrary quantum state $|\psi\rangle = \alpha|0\rangle + \beta|1\rangle$.

---

### Circuit-Level Verification Overview
We construct two separate 1-qubit circuits initialized in $|0\rangle$:
- **Circuit 1 ($HZH$)**: $|0\rangle \xrightarrow{\quad H \quad} |+\rangle \xrightarrow{\quad Z \quad} |-\rangle \xrightarrow{\quad H \quad} |1\rangle$
- **Circuit 2 ($X$)**: $|0\rangle \xrightarrow{\quad X \quad} |1\rangle$

The resulting statevectors are extracted using `Statevector.from_instruction()` and verified for numerical equality using NumPy's `np.allclose()`.

---

### Matrix-Level Verification Overview
The standard unitary matrix representations in the computational basis $\{|0\rangle, |1\rangle\}$ are:
$$H = \frac{1}{\sqrt{2}} \begin{pmatrix} 1 & 1 \\ 1 & -1 \end{pmatrix}, \quad Z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad X = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}$$

Evaluating the matrix product:
$$HZH = H @ Z @ H = \left[ \frac{1}{\sqrt{2}} \begin{pmatrix} 1 & 1 \\ 1 & -1 \end{pmatrix} \right] \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix} \left[ \frac{1}{\sqrt{2}} \begin{pmatrix} 1 & 1 \\ 1 & -1 \end{pmatrix} \right] = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix} = X$$
The product matrix is compared against $X$ using `np.allclose()`.

---

### Tools and Libraries
- **Qiskit**: Open-source quantum SDK used to define and assemble quantum circuits (`QuantumCircuit`).
- **qiskit.quantum_info.Statevector**: Module used to extract exact statevectors analytically directly from quantum circuit instructions.
- **Qiskit Aer (`AerSimulator`)**: Included in the environment for quantum simulation capabilities.
- **NumPy**: Fundamental library used for matrix definitions, matrix multiplication (`@`), and floating-point equivalence checks (`np.allclose`).

---

## Implementation Setup

### Dependencies and Imports
Install and import required modules from Qiskit and NumPy.

In [1]:
!pip install qiskit qiskit-aer -q

In [2]:
import random
import numpy as np

from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector
from qiskit_aer import AerSimulator

/var/folders/yp/078pyxw11mq6g7sd_2ty18z80000gn/T/ipykernel_27352/2087795024.py:4: DeprecationWarning: Using Qiskit with Python 3.9 is deprecated as of the 2.1.0 release. Support for running Qiskit with Python 3.9 will be removed in the 2.3.0 release, which coincides with when Python 3.9 goes end of life.
  from qiskit import QuantumCircuit


### Statevector Inspection Helper Function
Define a reusable helper function `show_state(circuit, title)` to display the ASCII circuit diagram and extract the statevector.

In [3]:
def show_state(circuit, title):
    state = Statevector.from_instruction(circuit)
    print("="*60)
    print(title)
    print(circuit.draw())
    print("\nStatevector:")
    print(state)
    print("="*60)
    return state

---

## Circuit Verification

### Construct the HZH Circuit
Initialize a 1-qubit quantum circuit (`QuantumCircuit(1)`) in state $|0\rangle$ and sequentially apply the gate sequence:
$$|0\rangle \xrightarrow{\quad H \quad} |+\rangle \xrightarrow{\quad Z \quad} |-\rangle \xrightarrow{\quad H \quad} |1\rangle$$

In [4]:
qc_hzh = QuantumCircuit(1)

qc_hzh.h(0)

qc_hzh.z(0)

qc_hzh.h(0)

state_hzh = show_state(qc_hzh,"HZH Circuit")

HZH Circuit
   ┌───┐┌───┐┌───┐
q: ┤ H ├┤ Z ├┤ H ├
   └───┘└───┘└───┘

Statevector:
Statevector([-2.23711432e-17+0.j,  1.00000000e+00+0.j],
            dims=(2,))


### Construct the Pauli-X Circuit
Initialize a 1-qubit quantum circuit (`QuantumCircuit(1)`) in state $|0\rangle$ and apply a single Pauli-X gate:
$$|0\rangle \xrightarrow{\quad X \quad} |1\rangle$$

In [5]:
qc_x2 = QuantumCircuit(1)

qc_x2.x(0)

state_x2 = show_state(qc_x2,"X Gate Circuit")

X Gate Circuit
   ┌───┐
q: ┤ X ├
   └───┘

Statevector:
Statevector([0.+0.j, 1.+0.j],
            dims=(2,))


---

## Compare the Statevectors

Compare the statevector obtained from the $HZH$ circuit (`state_hzh.data`) with that from the Pauli-X circuit (`state_x2.data`) using `np.allclose()` to confirm numerical equivalence.

In [6]:
print("HZH State:")
print(state_hzh.data)

print("\nX Gate State:")
print(state_x2.data)

print("\nEquivalent?")

print(np.allclose(state_hzh.data,state_x2.data))

HZH State:
[-2.23711432e-17+0.j  1.00000000e+00+0.j]

X Gate State:
[0.+0.j 1.+0.j]

Equivalent?
True


---

## Matrix Representation

Define the analytical matrix representations of the Hadamard ($H$), Pauli-Z ($Z$), and Pauli-X ($X$) operators in the computational basis:
$$H = \frac{1}{\sqrt{2}} \begin{pmatrix} 1 & 1 \\ 1 & -1 \end{pmatrix}, \quad Z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad X = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}$$

---

## Verify HZH = X Algebraically

Compute the matrix product $HZH = H @ Z @ H$ using NumPy's matrix multiplication operator `@` and verify that $H @ Z @ H = X$ using `np.allclose()`.

In [7]:
print("Analytical Proof")

print()

print("Hadamard Matrix:")

print(np.array([[1,1],[1,-1]])/np.sqrt(2))

print()

print("Z Matrix:")

print(np.array([[1,0],[0,-1]]))

print()

print("X Matrix:")

print(np.array([[0,1],[1,0]]))

print()

H = np.array([[1,1],[1,-1]])/np.sqrt(2)

Z = np.array([[1,0],[0,-1]])

HZH = H @ Z @ H

print("HZH Matrix:")

print(HZH)

print()

print("Is HZH equal to X?")

print(np.allclose(HZH,np.array([[0,1],[1,0]])))

Analytical Proof

Hadamard Matrix:
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

Z Matrix:
[[ 1  0]
 [ 0 -1]]

X Matrix:
[[0 1]
 [1 0]]

HZH Matrix:
[[-2.23711432e-17  1.00000000e+00]
 [ 1.00000000e+00 -2.23711432e-17]]

Is HZH equal to X?
True


---

## Conclusion

- The notebook verifies the fundamental quantum gate identity **$HZH = X$** through two distinct and rigorous approaches:
  1. **Circuit Statevector Simulation**: Demonstrates that the composite sequence $H \to Z \to H$ applied to $|0\rangle$ yields the $|1\rangle$ computational basis statevector, identically matching the action of a single Pauli-X gate on $|0\rangle$.
  2. **Direct Matrix Multiplication**: Establishes operator equivalence by proving that $H @ Z @ H$ equals $X$ as a matrix identity, which guarantees that $HZH|\psi\rangle = X|\psi\rangle$ holds for all arbitrary single-qubit states $|\psi\rangle$.
- In both cases, verification using `np.allclose()` confirms complete numerical and analytical equivalence within floating-point tolerance.